stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw_data.csv
    outs:
      - data/processed_data.csv
  train:
    cmd: python src/train.py
    deps:
      - data/processed_data.csv
      - src/lightning_modules/
      - configs/
    outs:
      - models/model.ckpt